CREATE TABLE IF NOT EXISTS Users (
    user_id INT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    balance DECIMAL(10, 2) DEFAULT 0.00,
    current_points INT DEFAULT 0,
    credit_limit DECIMAL(10, 2) DEFAULT 10000.00
);

CREATE TABLE IF NOT EXISTS Transactions (
    transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('Pending','Paid','Voided','Refunded')),
    merchant VARCHAR(50),
    point_change INT DEFAULT 0,
    source_transaction_id BIGINT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(user_id),
    FOREIGN KEY (source_transaction_id) REFERENCES Transactions(transaction_id)
);

CREATE TABLE IF NOT EXISTS Points (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    transaction_id BIGINT,
    change_amount INT NOT NULL,
    reason VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(user_id),
    FOREIGN KEY (transaction_id) REFERENCES Transactions(transaction_id)
);

CREATE INDEX IF NOT EXISTS idx_transactions_risk_control 
ON Transactions (user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_transactions_duplicate_check 
ON Transactions (user_id, merchant, created_at);